// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: openshell.proto

package openshellv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IssueSandboxToken request. The caller is identified by its SA-token bearer
// credential, so the request body carries no fields.
type IssueSandboxTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSandboxTokenRequest) Reset() {
	*x = IssueSandboxTokenRequest{}
	mi := &file_openshell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSandboxTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSandboxTokenRequest) ProtoMessage() {}

func (x *IssueSandboxTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSandboxTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueSandboxTokenRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{0}
}

// IssueSandboxToken response.
type IssueSandboxTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway-minted JWT bound to the calling sandbox's UUID.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Absolute expiry of the issued token, milliseconds since the epoch. 0 means
	// the token is non-expiring.
	ExpiresAtMs   int64 `protobuf:"varint,2,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSandboxTokenResponse) Reset() {
	*x = IssueSandboxTokenResponse{}
	mi := &file_openshell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSandboxTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSandboxTokenResponse) ProtoMessage() {}

func (x *IssueSandboxTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSandboxTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueSandboxTokenResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{1}
}

func (x *IssueSandboxTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueSandboxTokenResponse) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

type GetSandboxProviderEnvironmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sandbox ID.
	SandboxId     string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxProviderEnvironmentRequest) Reset() {
	*x = GetSandboxProviderEnvironmentRequest{}
	mi := &file_openshell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxProviderEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxProviderEnvironmentRequest) ProtoMessage() {}

func (x *GetSandboxProviderEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxProviderEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxProviderEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{2}
}

func (x *GetSandboxProviderEnvironmentRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxProviderEnvironmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider credential environment variables.
	Environment map[string]string `protobuf:"bytes,1,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Fingerprint for the provider credential inputs that produced environment.
	ProviderEnvRevision uint64 `protobuf:"varint,2,opt,name=provider_env_revision,json=providerEnvRevision,proto3" json:"provider_env_revision,omitempty"`
	// Expiration timestamps for returned environment variables.
	CredentialExpiresAtMs map[string]int64 `protobuf:"bytes,3,rep,name=credential_expires_at_ms,json=credentialExpiresAtMs,proto3" json:"credential_expires_at_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSandboxProviderEnvironmentResponse) Reset() {
	*x = GetSandboxProviderEnvironmentResponse{}
	mi := &file_openshell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxProviderEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxProviderEnvironmentResponse) ProtoMessage() {}

func (x *GetSandboxProviderEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxProviderEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxProviderEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{3}
}

func (x *GetSandboxProviderEnvironmentResponse) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *GetSandboxProviderEnvironmentResponse) GetProviderEnvRevision() uint64 {
	if x != nil {
		return x.ProviderEnvRevision
	}
	return 0
}

func (x *GetSandboxProviderEnvironmentResponse) GetCredentialExpiresAtMs() map[string]int64 {
	if x != nil {
		return x.CredentialExpiresAtMs
	}
	return nil
}

var File_openshell_proto protoreflect.FileDescriptor

const file_openshell_proto_rawDesc = "" +
	"\n" +
	"\x0fopenshell.proto\x12\fopenshell.v1\"\x1a\n" +
	"\x18IssueSandboxTokenRequest\"U\n" +
	"\x19IssueSandboxTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\"\n" +
	"\rexpires_at_ms\x18\x02 \x01(\x03R\vexpiresAtMs\"E\n" +
	"$GetSandboxProviderEnvironmentRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xd7\x03\n" +
	"%GetSandboxProviderEnvironmentResponse\x12f\n" +
	"\venvironment\x18\x01 \x03(\v2D.openshell.v1.GetSandboxProviderEnvironmentResponse.EnvironmentEntryR\venvironment\x122\n" +
	"\x15provider_env_revision\x18\x02 \x01(\x04R\x13providerEnvRevision\x12\x87\x01\n" +
	"\x18credential_expires_at_ms\x18\x03 \x03(\v2N.openshell.v1.GetSandboxProviderEnvironmentResponse.CredentialExpiresAtMsEntryR\x15credentialExpiresAtMs\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\x1aCredentialExpiresAtMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xfc\x01\n" +
	"\tOpenShell\x12\x88\x01\n" +
	"\x1dGetSandboxProviderEnvironment\x122.openshell.v1.GetSandboxProviderEnvironmentRequest\x1a3.openshell.v1.GetSandboxProviderEnvironmentResponse\x12d\n" +
	"\x11IssueSandboxToken\x12&.openshell.v1.IssueSandboxTokenRequest\x1a'.openshell.v1.IssueSandboxTokenResponseB\xcc\x01\n" +
	"\x10com.openshell.v1B\x0eOpenshellProtoP\x01ZWgithub.com/kagenti/kagenti-extensions/authbridge/authlib/openshell/genproto/openshellv1\xa2\x02\x03OXX\xaa\x02\fOpenshell.V1\xca\x02\fOpenshell\\V1\xe2\x02\x18Openshell\\V1\\GPBMetadata\xea\x02\rOpenshell::V1b\x06proto3"

var (
	file_openshell_proto_rawDescOnce sync.Once
	file_openshell_proto_rawDescData []byte
)

func file_openshell_proto_rawDescGZIP() []byte {
	file_openshell_proto_rawDescOnce.Do(func() {
		file_openshell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_proto_rawDesc), len(file_openshell_proto_rawDesc)))
	})
	return file_openshell_proto_rawDescData
}

var file_openshell_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_openshell_proto_goTypes = []any{
	(*IssueSandboxTokenRequest)(nil),              // 0: openshell.v1.IssueSandboxTokenRequest
	(*IssueSandboxTokenResponse)(nil),             // 1: openshell.v1.IssueSandboxTokenResponse
	(*GetSandboxProviderEnvironmentRequest)(nil),  // 2: openshell.v1.GetSandboxProviderEnvironmentRequest
	(*GetSandboxProviderEnvironmentResponse)(nil), // 3: openshell.v1.GetSandboxProviderEnvironmentResponse
	nil, // 4: openshell.v1.GetSandboxProviderEnvironmentResponse.EnvironmentEntry
	nil, // 5: openshell.v1.GetSandboxProviderEnvironmentResponse.CredentialExpiresAtMsEntry
}
var file_openshell_proto_depIdxs = []int32{
	4, // 0: openshell.v1.GetSandboxProviderEnvironmentResponse.environment:type_name -> openshell.v1.GetSandboxProviderEnvironmentResponse.EnvironmentEntry
	5, // 1: openshell.v1.GetSandboxProviderEnvironmentResponse.credential_expires_at_ms:type_name -> openshell.v1.GetSandboxProviderEnvironmentResponse.CredentialExpiresAtMsEntry
	2, // 2: openshell.v1.OpenShell.GetSandboxProviderEnvironment:input_type -> openshell.v1.GetSandboxProviderEnvironmentRequest
	0, // 3: openshell.v1.OpenShell.IssueSandboxToken:input_type -> openshell.v1.IssueSandboxTokenRequest
	3, // 4: openshell.v1.OpenShell.GetSandboxProviderEnvironment:output_type -> openshell.v1.GetSandboxProviderEnvironmentResponse
	1, // 5: openshell.v1.OpenShell.IssueSandboxToken:output_type -> openshell.v1.IssueSandboxTokenResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_openshell_proto_init() }
func file_openshell_proto_init() {
	if File_openshell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_proto_rawDesc), len(file_openshell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openshell_proto_goTypes,
		DependencyIndexes: file_openshell_proto_depIdxs,
		MessageInfos:      file_openshell_proto_msgTypes,
	}.Build()
	File_openshell_proto = out.File
	file_openshell_proto_goTypes = nil
	file_openshell_proto_depIdxs = nil
}
