// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: openshell.proto

package openshellv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenShell_GetSandboxProviderEnvironment_FullMethodName = "/openshell.v1.OpenShell/GetSandboxProviderEnvironment"
	OpenShell_IssueSandboxToken_FullMethodName             = "/openshell.v1.OpenShell/IssueSandboxToken"
)

// OpenShellClient is the client API for OpenShell service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Minimal subset of the OpenShell gateway API: only the two RPCs the AuthBridge
// placeholder-resolve gateway resolver calls, plus their messages. The full
// OpenShell API is intentionally NOT vendored here. The package, service, RPC,
// and message names and field numbers match the gateway's openshell.v1.OpenShell
// service exactly, so the wire contract is unchanged.
type OpenShellClient interface {
	// Get provider environment for a sandbox (called by the sandbox supervisor, and
	// by an AuthBridge sidecar, at startup). Restricted to the sandbox's own identity.
	GetSandboxProviderEnvironment(ctx context.Context, in *GetSandboxProviderEnvironmentRequest, opts ...grpc.CallOption) (*GetSandboxProviderEnvironmentResponse, error)
	// Mint a gateway JWT bound to the calling sandbox's identity (Bearer SA token).
	IssueSandboxToken(ctx context.Context, in *IssueSandboxTokenRequest, opts ...grpc.CallOption) (*IssueSandboxTokenResponse, error)
}

type openShellClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenShellClient(cc grpc.ClientConnInterface) OpenShellClient {
	return &openShellClient{cc}
}

func (c *openShellClient) GetSandboxProviderEnvironment(ctx context.Context, in *GetSandboxProviderEnvironmentRequest, opts ...grpc.CallOption) (*GetSandboxProviderEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxProviderEnvironmentResponse)
	err := c.cc.Invoke(ctx, OpenShell_GetSandboxProviderEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openShellClient) IssueSandboxToken(ctx context.Context, in *IssueSandboxTokenRequest, opts ...grpc.CallOption) (*IssueSandboxTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueSandboxTokenResponse)
	err := c.cc.Invoke(ctx, OpenShell_IssueSandboxToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenShellServer is the server API for OpenShell service.
// All implementations must embed UnimplementedOpenShellServer
// for forward compatibility.
//
// Minimal subset of the OpenShell gateway API: only the two RPCs the AuthBridge
// placeholder-resolve gateway resolver calls, plus their messages. The full
// OpenShell API is intentionally NOT vendored here. The package, service, RPC,
// and message names and field numbers match the gateway's openshell.v1.OpenShell
// service exactly, so the wire contract is unchanged.
type OpenShellServer interface {
	// Get provider environment for a sandbox (called by the sandbox supervisor, and
	// by an AuthBridge sidecar, at startup). Restricted to the sandbox's own identity.
	GetSandboxProviderEnvironment(context.Context, *GetSandboxProviderEnvironmentRequest) (*GetSandboxProviderEnvironmentResponse, error)
	// Mint a gateway JWT bound to the calling sandbox's identity (Bearer SA token).
	IssueSandboxToken(context.Context, *IssueSandboxTokenRequest) (*IssueSandboxTokenResponse, error)
	mustEmbedUnimplementedOpenShellServer()
}

// UnimplementedOpenShellServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenShellServer struct{}

func (UnimplementedOpenShellServer) GetSandboxProviderEnvironment(context.Context, *GetSandboxProviderEnvironmentRequest) (*GetSandboxProviderEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxProviderEnvironment not implemented")
}
func (UnimplementedOpenShellServer) IssueSandboxToken(context.Context, *IssueSandboxTokenRequest) (*IssueSandboxTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueSandboxToken not implemented")
}
func (UnimplementedOpenShellServer) mustEmbedUnimplementedOpenShellServer() {}
func (UnimplementedOpenShellServer) testEmbeddedByValue()                   {}

// UnsafeOpenShellServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenShellServer will
// result in compilation errors.
type UnsafeOpenShellServer interface {
	mustEmbedUnimplementedOpenShellServer()
}

func RegisterOpenShellServer(s grpc.ServiceRegistrar, srv OpenShellServer) {
	// If the following call pancis, it indicates UnimplementedOpenShellServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenShell_ServiceDesc, srv)
}

func _OpenShell_GetSandboxProviderEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxProviderEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenShellServer).GetSandboxProviderEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenShell_GetSandboxProviderEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenShellServer).GetSandboxProviderEnvironment(ctx, req.(*GetSandboxProviderEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenShell_IssueSandboxToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueSandboxTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenShellServer).IssueSandboxToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenShell_IssueSandboxToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenShellServer).IssueSandboxToken(ctx, req.(*IssueSandboxTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenShell_ServiceDesc is the grpc.ServiceDesc for OpenShell service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenShell_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openshell.v1.OpenShell",
	HandlerType: (*OpenShellServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSandboxProviderEnvironment",
			Handler:    _OpenShell_GetSandboxProviderEnvironment_Handler,
		},
		{
			MethodName: "IssueSandboxToken",
			Handler:    _OpenShell_IssueSandboxToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openshell.proto",
}
