name: Spellcheck Action
on:
  pull_request:
    branches:
      - main
      - "release-*"
  push:
    branches:
      - main

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@0.36.0
        with:
          config_path: .github/spellcheck/.spellcheck.yml
          task_name: Markdown
